### ISSUE TITLE
ERROR:"ReferenceError: require is not defined" while using moment on Log Agent

### ISSUE THREAD

**Issue by raovaibhav** [sematext/logagent-js#100]
I am trying to modify the value of @timestamp in my logs to an epoch (UNIX format) but when i use moment in my pattern.yml I get the below error with logagent.

ERROR:"ReferenceError: require is not defined"

npm -v : 3.10.10
sudo npm i moment -g:
/usr/lib
âââ moment@2.19.1

Code snippet of transform from my yml:

transform: !!js/function >
  function (p) {
    moment = require('moment')
    p['@timestamp'] = moment().valueOf()
    }

Am i missing some package or not doing this right?

**Comment by raovaibhav** [comment]
Can Anyone Help on this? More information if required:

MACHINE: uname -a : Linux raova02-S7229 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

STEPS followed for installation:
NODE JS:
curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
sudo yum -y install nodejs

LogAgent:
Install Logagent npm package
sudo npm i -g @sematext/logagent 

Any Help would be appreciated.

-Vaibhav

**Comment by fbalicchia** [comment]
Hi @raovaibhav,
could you please provide us a complete yml file and command you use to instruct logagent ?
I'll check on it asp
Regards

**Comment by raovaibhav** [comment]
Thanks for the response @fbalicchia 
Heres the info requested:

Command to test : cat /opt/apache_access_new.txt | /usr/bin/logagent -p -n myapp -f /opt/new.yml --verbose

Usually i use the systemctl service only to start LA and post to ES but using the above commands to test the patterns/fields

**Content of logfile (apache_access_new.txt)**
62.209.128.4 - - [12/Oct/2017:10:00:07 -0700] "GET /servicedesk/web/jsp/apps/OrderStatus.jsp?orderid=12PPHUA2321 HTTP/1.1" 200 75 0.007
62.209.128.5 - - [12/Oct/2017:10:00:08 -0700] "GET /servicedesk/web/jsp/apps/OrderStatus.jsp?orderid=12PPHUA2321 HTTP/1.1" 200 75 0.007
62.209.128.6 - - [12/Oct/2017:10:00:09 -0700] "GET /servicedesk/web/jsp/apps/OrderStatus.jsp?orderid=12PPHUA2321 HTTP/1.1" 200 75 0.007

**Pattern File:**
[root@raova02-S7229 opt]# cat new.yml
# Sensitive data can be replaced with a hashcode (sha1)
# it applies to fields matching the field names by a regular expression
# Note: this function is not optimized (yet) and might take 10-15% of performance
#autohash: !!js/regexp /user|password|email|credit_card_number|payment_info/i
autohash: false

# set this to false when autohash fields
# the original line might include sensitive data!
originalLine: false
suppress: false

# activate GeoIP lookup
geoIP: true

# Logagent updates GeoIP DB files automatically
# pls. note write access to this directory is required
maxmindDbDir: /tmp/

debug: false

# The global transform function is called for each parsed line.
# A good place to do add global fields, custom date processing, or special parsers.
globalTransform: !!js/function >
 function (source, parsedObject) {
  parsedObject.tenant_id = "Test"
  parsedObject.logtype = parsedObject._type
  parsedObject.file = parsedObject.logSource
  parsedObject._type = "data"
  //delete parsedObject._type
  delete parsedObject.logSource
  //delete parsedObject['@timestamp']
 }

patterns:
 - # APACHE  Web Logs
  sourceName: !!js/regexp /.*apache.*|.*myapp.*/
  match:
    # Common Log Format
    - regex:        !!js/regexp /([0-9a-f.:]+)\s+(-|.+?)\s+(-|.+?)\s+\[([0-9]{2}\/[a-z]{3}\/[0-9]{4}\:[0-9]{2}:[0-9]{2}:[0-9]{2}[^\]]*)\] \"(\S+?)\s(\S*?)\s{0,1}(\S+?)\" ([0-9|\-]+) ([0-9|\-]+) ([0-9|\.\-]+)/i
      type: apache_access
      fields:       [clientip,remote_id,user,ts,http_method,request,http_version,response_code,bytes,response_time]
      dateFormat: DD/MMM/YYYY:HH:mm:ss ZZ
      # lookup geoip info for the field client_ip
      geoIP: client_ip
      transform: !!js/function >
        function (p) {
         moment = require('moment')
         p['@timestamp'] = moment().valueOf()
         //p['@timestamp'] = "1509527570570"
        }

**Comment by fbalicchia** [comment]
Hi,
I've reproduce the behaviour, moment is already present as Logagent dependency
[dependency](https://github.com/sematext/logagent-js/blob/master/package.json#L81 )
but as you can saw it can't be found at runtime cause is not in scope.
I try figure out a way to define it with JS-YAML but.... Sorry I can’t find 
a solution

**Comment by raovaibhav** [comment]
Hi @fbalicchia ,
Actually it states it the example pattern files [https://github.com/sematext/logagent-js/blob/69fc9456929733de6c01c0dab159dd39f0cb684f/patterns.yml#L62](url) about moment being supported as a JS-YAML configuration?

Also i have seen many suggestions on using moments in the conf file to parse date in logagents github threads.

So, I am guessing this is supported but is not achievable by the way i am doing this? I can follow any other method for downloading and running LA if it will make the "moments" configuration work.
Let me know if you know of some other mechanism for LA to be able to include moment at runtime?

BR,

**Comment by megastef** [comment]
@raovaibhav Note that JS-YAML limits the JS function for security reasons. For the globalTransform we bound moment to the function - you can use moment via `this.moment`. Currently, there is no such binding for patterns 'transform' functions as far I know. 

We will check if we could provide general "require" in transform functions - for complex actions you could always create e.g. output filter plugins as separate `npm` packages. 

In your specific case you could convert the `@timestamp` Date field  with the Date function "getTime" and divide the value by 1000 to get seconds:

```
parsed['@timestamp'] = parsed['@timestamp'].getTime()/1000
```

**Comment by Faleij** [comment]
@raovaibhav Although ```require``` is undefined on global scope it is still defined on ```process.mainModule``` so you could require moment like so: ```const moment = process.mainModule.require('moment');```

**Comment by otisg** [comment]
Thanks @Faleij .  Can you confirm if that works for you, @raovaibhav ?

**Comment by raovaibhav** [comment]
Thanks @megastef and @Faleij , both the solutions work perfect. 

//Best Regards
