### ISSUE TITLE
Chat room for logagent-js

### ISSUE THREAD

**Issue by fbalicchia** [sematext/logagent-js#102]
Hi,
is possible to create  a chat room for logagent project using gitter for example ?

**Comment by otisg** [comment]
Would https://github.com/discourse/discourse be more or less desirable in your opinion?

**Comment by fbalicchia** [comment]
Hi, 
I suggest Gitter cause in other OS projects use that, honestly I did not know it
but It seems has a lot cool features, but sorry for stupid question but do you have 
already installed it ?
From my point of view that can be useful for interact with the community for suggestions, configuration issues etc.etc

**Comment by otisg** [comment]
We did not set u Gitter, but we are thinking about something like Discourse, not just for Logagent, but for other open-source and non open-sources tools and products we provide.

**Comment by otisg** [comment]
We have https://groups.google.com/forum/#!forum/logagent for now.  May be replaced by something else in the future.
