### ISSUE TITLE
Separate Docker Hub README 

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#105]
Please note the automated build uses Logagent Readme in Docker Hub. 
https://hub.docker.com/r/sematext/logagent/

We should create a separate [Readme](https://github.com/sematext/logagent-js/blob/master/docker-hub-readme.md) only for Docker hub. This means we should move Dockerfile, run.sh and README to a separate Github repository. 

See related Docker Hub issue: https://forums.docker.com/t/automated-build-custom-readme-md-file/36006

**Comment by otisg** [comment]
It should probably just be a separate README for Docker, not Docker Hub, right?

**Comment by megastef** [comment]
Finally done: https://hub.docker.com/r/sematext/logagent/

All relevant files moved into dockerhub subdirectory. 
https://github.com/sematext/logagent-js/tree/master/dockerhub

Docker Hub automated build is configured to use the "dockerhub" folder. The only disadvantage, is the duplication of a file. The patterns.yml file is a copy from the package root directory.
