### ISSUE TITLE
Add simple configuration setting for severity filter

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#108]
Logagent should be able to filter log messages by severity  / log level. This is possible via JS function or input-grep filter, it would be more convenient and efficient to define filters for the severity field.

**Comment by otisg** [comment]
Would it make sense to simply document how to filter and provide examples how to filter by severity or any other field instead of adding code that has hard-coded "severity" and such?

**Comment by megastef** [comment]
Closing, the drop-events output-filter can be used to drop messages my any field value. 
https://sematext.com/docs/logagent/output-filter-dropevents/
