### ISSUE TITLE
Support multiple tokens for tail-file mode

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#11]
Currently the logagent-js setup running as Linux service supports only one Logsene token/elasticserach index. Logs are stored with differten _type in Logsne/Elasticsearch, but it would be helpful to map file names and tokens somehow to send different logs to separate indices.

**Comment by otisg** [comment]
Prefix the file with token, like token:/path/to/file.log, so if there is a ":" in this string, split it and first one is token, the second one path.  In case of Logsene tokens, one could also validate the format (4 dashes?) and length.

**Comment by megastef** [comment]
The new config format supports to send logs to separate indices. A regular expression can be used to identify log file names for each index.

```
output:
  # index logs in Elasticsearch or Logsene
  elasticsearch: 
    url: https://logsene-receiver.sematext.com
    # default index to use
    index: YOUR_DEFAULT_INDEX # for all logs, which don't match in indices section
    indices: 
      4f70a0c7-9458-43e2-bbc5-xxx: 
      # list of RegEx matching logSource / filename  
      # all logs from this source will be indexed to above index
        - .*nginx.*
        - .*access.*
      999532c9-18f1-4c4b-8753-xxx: 
        - mysql|mongodb|postgress```
