### ISSUE TITLE
Add MQTT Input Plugin

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#114]

**Comment by megastef** [comment]
We have 2 implementations:
1) [MQTT client](https://www.npmjs.com/package/mqtt) as subscriber for N topics using any 3rd party MQTT broker. See [code](https://github.com/sematext/logagent-js/blob/master/lib/plugins/input/mqtt-client.js) & [documentation](https://github.com/sematext/docs/blob/master/docs/logagent/input-plugin-mqtt-client.md) 
2) Running embedded [MQTT Broker](https://www.npmjs.com/package/mosca) (server), which emits each received event to LA pipeline. See [code](https://github.com/sematext/logagent-js/blob/master/lib/plugins/input/mqtt-broker.js) & [documentation](https://github.com/sematext/docs/blob/master/docs/logagent/input-plugin-mqtt-broker.md)
