### ISSUE TITLE
 BrokerNotAvailableError: Broker not available

### ISSUE THREAD

**Issue by vietlhsa** [sematext/logagent-js#119]
**I try connect logagent to kafka apache server**
**First I install Logagent and the Kafka plugins (assuming nodejs is installed already):**
npm i -g '@'sematext/logagent
npm i -g logagent-output-kafka
npm i -g logagent-input-kafka
**Then, I created file logagent-kafka-output.yml like you showed:**
options:
includeOriginalLine: false

input:
stdin: true

output:
kafka:
module: logagent-output-kafka
host: localhost
port: 9092
topic: test
requireAcks: 1
sslEnable: false
sslOptions:
- rejectUnauthorized: false
**I'm ready run server kafka**
![image](https://user-images.githubusercontent.com/16033981/35138174-d6106b3e-fd1f-11e7-830a-819695dccd01.png)
**and created topic test**
![image](https://user-images.githubusercontent.com/16033981/35138179-ddea019e-fd1f-11e7-9e8e-323fb785e24d.png)
**finally, i run command "logagent -c logagent-kafka-output.yml" and recived erros:**
![image](https://user-images.githubusercontent.com/16033981/35138187-e731fd2e-fd1f-11e7-9cf7-0358276a83ba.png)
**How I can fix it, please show me?**

**Comment by fbalicchia** [comment]
Hi @vietlhsa , 
which version of Apache Kafka do you use ?

**Comment by vietlhsa** [comment]
Hi Filipo Balicchia, thank you very much.
I use kafka_2.11-0.11.0.2.jar.

Lê Hải Việt
email: vietlhsa@gmail.com
Skyper: vietlh1989

On Fri, Jan 19, 2018 at 3:19 PM, filippo balicchia <notifications@github.com

**Comment by megastef** [comment]
@vietlhsa   Please note the discussion here: https://github.com/fbalicchia/logagent-output-kafka/issues/2 - it looks the Node-Kafka API changed and I think a workaround with the current version is to pass Zookeeper host & port instead Kafka broker host & port.

**Comment by megastef** [comment]
Closing in favour of  fbalicchia/logagent-output-kafka#2
