### ISSUE TITLE
Create docker input plugin

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#131]
Similar to Sematext Docker Agent: 
- Capture logs from docker remote API 
- Parse messages with Logagent parser
- Enrich logs with container labels, env vars etc. 
- Enrich logs with Kubernetes and Swarm metadata

**Comment by wildaces215** [comment]
Is this issue open I would like to tackle it

**Comment by megastef** [comment]
Plugin docs: https://sematext.com/docs/logagent/input-plugin-dockerlogs/

Published in Docker image to collect Docker logs: https://hub.docker.com/r/sematext/logagent/
