### ISSUE TITLE
Using logagent in a programmatic way inside a Nodejs application

### ISSUE THREAD

**Issue by Allaoua9** [sematext/logagent-js#133]
The doc says : "Node.js module to integrate parsers into Node.js programs"

Are there any detailed doc/examples that show how to use Logagent inside a Nodejs application ?

**Comment by megastef** [comment]
You can use the parser as library in nodejs programs. See e.g. https://sematext.com/docs/logagent/parser/#nodejs-api-for-the-parser

**Comment by megastef** [comment]
@Allaoua9 please note the documentation uses an obsolete package name. Use 
```
npm i @sematext/logagent --save
``` 
to install the package in your develeopment environment. 

We will update the documentation asap: https://sematext.com/docs/logagent/parser/#nodejs-api-for-the-parser

Note thre is anothe way to use Logagent - implement a plugin for input or output or filtering. 
We could help if you tell us, what you plan to implement.

**Comment by megastef** [comment]
Closing. Any plugin could be added or used in a programmable way, and the parser.
