### ISSUE TITLE
Elasticsearch document ID and version

### ISSUE THREAD

**Issue by rucciva** [sematext/logagent-js#134]
is it possible to manage document ID and Version in elasticsearch ouput plugins?

**Comment by megastef** [comment]
Please explain, what you like to achieve. 

I think you could set the `_id` value in the parsed object to control document ID. As far I see we don't have an option to set the _version for docs, which is typically managed by Elasticsearch itself. 

See: 
https://github.com/sematext/logsene-js/blob/master/index.js#L307-L309
https://github.com/sematext/logsene-js/blob/master/index.js#L343-L345

**Comment by rucciva** [comment]
i would like to achieve insert or replace scenario (thus need to specify id) with the possibilities that data with the same id might come unordered regarding their time (thus need to specify external version)  

The scenario is more like this, data x is created at time y but then updated after y (y1). Both  events were logged and sent to kafka topic with multiple partition. The logagent will receive from that topic and forward it to elasticsearch. I just want to make sure data x that will be saved to elasticsearch resemble it state at y1, not at y, despite the possibilities that event containing state at y1 processed earlier than event containing state at y.

currently, we achieved that using logstash [version](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-version) and [external-version](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-version_type) options of elasticsearch output plugin. We would like to see wether we can replace logstash all along with logagent for better memory footprint.

BTW, i have the tried the _id fields and it works, thanks

**Comment by megastef** [comment]
@rucciva Is anything missing in Logagent? Or can we close the issue? 

Should Logagent support `_verison` and `version_type` fields in the index operation? 
We could add support for those fields here: https://github.com/sematext/logsene-js/blob/master/index.js#L343

**Comment by rucciva** [comment]
yes we can close it,
thank you
