### ISSUE TITLE
AWS Elasticsearch plugin: Index name to be with date

### ISSUE THREAD

**Issue by rizwanzfr** [sematext/logagent-js#144]
Hi, 
When I try to  index name generated with date in output section, it gives me error. Tried different formats like 
```output:
  aws-es:
    module: output-aws-elasticsearch
    index: test-yyyy.mm.dd 
    index: "test-%{+yyyy.mm.dd}"
```

But in vain. While same thing works well in filebeat like 
```
output.elasticsearch:
  # Array of hosts to connect to.
    index: "test-%{+YYYY.MM.dd}"
```

Please share the solution.

**Comment by otisg** [comment]
What is the error you are getting?  Could you please share that?

**Comment by rizwanzfr** [comment]
We get following error if we use index file format as 

`index: test-date +"%m-%d-%y"`

`2018-11-02T07:39:06.452Z aws-elasticsearch:[invalid_index_name_exception] Invalid index name [test-date +"%m-%d-%y"], must not contain the following characters [ , ", *, \, <, |, ,, >, /, ?],`

If we use simple index name as` test-yyyy-mm-dd,` 

logs start going to kibana but index created at kibana is same  `test-yyyy-mm-dd` rather than `test-2018-11-02`. Please provide some suggestion. Using logagent version `2.0.121` centos machine.

**Comment by megastef** [comment]
I think the date pattern is implemented in the elasticsearch output plugin, but not in the AWS Elasticsearch plugin.

**Comment by megastef** [comment]
We added a function to replace date pattern with the current date. 
@rizwanzfr please try the latest logagent version. 
`sudo npm i -g @sematext/logagent@2.0.124`

**Comment by megastef** [comment]
@rizwanzfr  please use following config (date format in upper-case): 
```
aws-es:
    module: output-aws-elasticsearch
    index: "test-YYYY.MM.DD"
```

**Comment by megastef** [comment]
@rizwanzfr Did you have a chance to try the new version? Can we close the issue?

**Comment by rizwanzfr** [comment]
Yes, the issue has been resolved by using above suggestion. Thanks
