### ISSUE TITLE
Rework logagent.conf to be a real config file

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#15]
The logagent.conf is not really a config currently. It's just a place where all command-line parameters can be stored.  This should probably be changed, so logagent.conf looks like a typical config file.

**Comment by hakman** [comment]
Big +1 from me!

**Comment by megastef** [comment]
This is na example of the new config file format: https://github.com/sematext/logagent-js/blob/master/config/example.yml

**Comment by otisg** [comment]
Does this let you tie certain inputs to filters/patterns to outputs and thus support N indices/tokens?

**Comment by megastef** [comment]
Yes. Multiple tokens are supported in the new config file format. Setup procedures needs to be changed to use the new config format.

**Comment by megastef** [comment]
Updated docs: https://github.com/sematext/logagent-js/blob/master/docs/cli-parameters.md#config-file
And example: https://github.com/sematext/logagent-js/blob/master/config/example.yml

To use the example: ```logagent --config config/example.yml```
