### ISSUE TITLE
Add boilerplate with multiple indices for shipping to multiple Logs Apps

### ISSUE THREAD

**Issue by adnanrahic** [sematext/logagent-js#159]
https://github.com/sematext/logagent-js/blob/ad4bdeff1baa606385124d55ab8d3856354cac4e/bin/logagent-setup.sh#L182
When running `sudo logagent-setup -i LOGS_TOKEN` we should also generate a section for multiple Elasticsearch endpoints and indices in the `logagent.conf` to make it easy for the customer to configure if needed. It can all be commented out to begin with. The goal is to have it in the configuration file for easy edits.

**Comment by otisg** [comment]
Sounds OK to me. @megastef ?

**Comment by megastef** [comment]
`logagent --writeConfig logagent.conf` generates a complete configuration file with all options.  See https://sematext.com/docs/logagent/cli-parameters/#command-line-parameters

**Comment by otisg** [comment]
@adnanrahic I think @megastef implemented something like this recently.... maybe in https://github.com/sematext/logagent-js/commit/c697139acd9b90ae2ababe724aa26a6f137e0d07 ?  Or is this only for multiple Receiver URLs?

**Comment by adnanrahic** [comment]
We have a feature for multiple ES indices as receivers. It's also documented [here](https://sematext.com/docs/logagent/config-file/#output) and [here](https://sematext.com/docs/logagent/output-elasticsearch/#log-routing-to-multiple-targets).

**Comment by megastef** [comment]
You can generate a complete config file with 
```
logagent --writeConfig <filename>
```

Including this section https://github.com/sematext/logagent-js/blob/master/config/example.yml#L1072-L1097

Shipping to multiple apps does not need https://github.com/sematext/logagent-js/commit/c697139acd9b90ae2ababe724aa26a6f137e0d07 which is for shipping to multiple servers.
