### ISSUE TITLE
Add support for multiple pattern files

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#16]
This way one wouldn't have to modify the original patterns.yml and count instead add custom ones.
e.g.
-f /path/to/patterns.yml,/path/to/my-custom-patterns.yml
or
-f /path/to/patterns.yml, -f /path/to/my-custom-patterns.yml

Order of files controls which patterns take priority if any definitions clash.  The latter overwrites the previously defined one(s), like CSS.

(btw. maybe -p would have been a better thing to use than -f?)

**Comment by megastef** [comment]
Multiple -f parameters are possible (master, not published on npm yet). The parameters -p is taken for pretty print json. Related to changes for the configuration files, we could review all CLI and config arguments.

**Comment by megastef** [comment]
Multiple pattern files can be defined in config files in 2.x
```
parser:
  patternFiles:
    # load a list of pattern files to parse logs
    # later files overwrite settings from previous files
    - patterns1.yml
    - patterns2.yml```
