### ISSUE TITLE
Implement journald input plugin

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#160]
Implement SDA journald TCP receiver in LA as a plugin.
Document helper service running basically “journalctl | netcat” as we did in CoreOS.

c.f. #42

**Comment by megastef** [comment]
With this https://github.com/sematext/logagent-js/commit/dd22fdd0862f3c5e210d39518d76b3efc987b42b we can use systemd.journald-upload.service to forward logs to logagent.

**Comment by megastef** [comment]
Released. Documentation https://sematext.com/docs/logagent/input-plugin-journald-upload/
