### ISSUE TITLE
Echo Logagent docs URL at the end of the setup

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#164]
I installed Logagent and got this:
$ sudo logagent-setup <token>

Set Logsene receiver url: https://logsene-receiver.sematext.com
/usr/bin/logagent
Create config file: /etc/sematext/logagent.conf
Config file /etc/sematext/logagent.conf exists already, creating backup file /etc/sematext/logagent.conf.bak
chown root /etc/sematext/logagent.conf
chmod 0600 /etc/sematext/logagent.conf

# Global options
options:
  # print stats every 60 seconds 
  printStats: 60
  # don't write parsed logs to stdout
  suppress: true
  # Enable/disable GeoIP lookups
  # Startup of logagent might be slower, when downloading the GeoIP database
  geoipEnabled: false
  # Directory to store Logagent status and temporary files
  # this is equals to LOGS_TMP_DIR env variable 
  diskBufferDir: /tmp/sematext-logagent

input:
  # a list of glob patterns to watch files to tail
  files:
    - '/var/log/**/*.log'

output:
  # index logs in Elasticsearch or Logsene
  elasticsearch: 
    module: elasticsearch
    url: https://logsene-receiver.sematext.com
    # default index (Logsene token) to use:
    index: <token>

Generate upstart script 
initctl reload-configuration
start logagent
logagent start/running, process 15882

At this point:
* I am _assuming_ the above config that was printed to console was actually added to /etc/sematext/logagent.conf .  OK, easy enough to check.
* I see Logagent is picking up everything from '/var/log/**/*.log', which is not quite what I wanted, but OK, I can go change that.
* I have no clue where to learn more about Logagent

Can we just print a pointer to sematext.com/docs/logagent at the very end?

**Comment by megastef** [comment]
Ok, added.
