### ISSUE TITLE
Remove or modify use of type for ElasticSearch output

### ISSUE THREAD

**Issue by jdeglopper** [sematext/logagent-js#166]
Elastic is deprecating the use of types, and they will be completely removed as of ElasticSearch 7.0, which has been released; see https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html and https://www.elastic.co/blog/index-type-parent-child-join-now-future-in-elasticsearch

Based on the error messages I'm seeing, and the code at https://github.com/sematext/logagent-js/blob/5e4f86c474c7009a937964a119dd80dda6c84f94/lib/plugins/output/elasticsearch.js#L119 it appears that the Elasticsearch output is setting multiple types:

`Error in Elasticsearch request:  source=logsene-js err=[object Object] /  message=HTTP status code:400 Error: {"type":"illegal_argument_exception","reason":"Rejecting mapping update to [logagent-2019.05.08] as the final mapping would have more than 1 type: [logs, access_log_combined]"} httpStatus=400 httpBody=[object Object] url=http://10.19.0.1:9200//logagent-2019.05.08/_bulk`

**Comment by megastef** [comment]
Thx. We need to check this again. Actually, the client library logsene-js has some code to use only one type: 
https://github.com/sematext/logsene-js/blob/master/index.js#L327-L332
