### ISSUE TITLE
Consider hot-reloading pattern files 

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#17]
Maybe check if the file was updated every 60 seconds and reload it only if it was indeed updated.

I was going to say this will help during pattern creation time, because one won't have to restart logagent after changing the patterns, but in that case 60 seconds would be too long to wait, so maybe that frequency should be configurable, so one can set it to e.g. 60s or even 300s for production, and 2s for dev.

**Comment by megastef** [comment]
We will use fs.watchFile in node, it creates an event when the file was changed.

**Comment by otisg** [comment]
Hope it lets you control how often it checks the file.  Or does it use inotify on Linux?

**Comment by megastef** [comment]
Finally fs.watch() is used. It generates event from inotify on Linux. 

This feature depends on the underlying operating system providing a way to be notified of filesystem changes.
- On Linux systems, this uses inotify
- On BSD systems, this uses kqueue
- On OS X, this uses kqueue for files and FSEvents for directories.
- On SunOS systems (including Solaris and SmartOS), this uses event ports.
- On Windows systems, this feature depends on ReadDirectoryChangesW.
- On Aix systems, this feature depends on [AHAFS], which must be enabled.

**Comment by otisg** [comment]
So it's always a notification - there is no polling?

**Comment by megastef** [comment]
No polling as far i know.
