### ISSUE TITLE
Add possibility to configure connection options in MQTT output plugin

### ISSUE THREAD

**Issue by tbarthelet** [sematext/logagent-js#172]
Hi,
When connecting to an external MQTT broker, additional information is usually required on top of broker url and port, like credentials for example.
It would be great to be able to pass the "options" object in the MQTT output plugin configuration which would be taken into account by the mqtt.connect function according to the mqtt.js doc:
https://www.npmjs.com/package/mqtt#client

**Comment by megastef** [comment]
Hi, it makes sense to add all options to the config.  
What happens when you add credentials in the URL? e.g. 

```
mqtt://user:password@127.0.0.1:1883
```

This could be a workaround until we have a new release.

**Comment by megastef** [comment]
Changes are made in commit https://github.com/sematext/logagent-js/commit/186930b425ac44505c6eb0a4160498d930932cc4

Please try by installing logagent from git `sudo npm install -g https://github.com/sematext/logagent-js.git` before we make a new release.

**Comment by tbarthelet** [comment]
It works great. Thank you very much for the quick fix!
