### ISSUE TITLE
TypeError: Cannot read property 'REMOVE_FIELDS' of undefined

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#174]
Known bug in [kubernetes-enrichment plugin](https://sematext.com/docs/logagent/output-filter-kubernetes/) in `sematext/logagent:3.0.0` and `v3.0.1`  - please upgrade to latest `sematext/logagent:3.0.2` or higher.

**Comment by megastef** [comment]
The command `kubectl delete pods -l app=sematext-agent` will delete running logagent pods and Kubernetes will restart the pods with the latest image.

**Comment by otisg** [comment]
If this was fixed in 3.0.2 can we close this issue?

**Comment by otisg** [comment]
@megastef & @adnanrahic do you know if this can be closed?

**Comment by adnanrahic** [comment]
It can be closed.
