### ISSUE TITLE
License clarity

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logagent-js#18]
Not sure if [this is cruft from a copy & paste](https://github.com/sematext/logagent-js/blob/6ecfd79f51b3bbb2cb60cd306bc5dcaea58ae58f/bin/logagent.js) or if intended for sematext customers only:

```
 * This source code may not be copied, reverse engineered, or altered for any purpose.
 * This source code is to be used exclusively by users and customers of Sematext.
 * Please see the full license (found in LICENSE in this distribution) for details on its license and the licenses of its dependencies.
```

Are non-sematext customers licensed to use this?  Thanks!

**Comment by megastef** [comment]
I think the initial copyright text in source code is from another project, the [Licence](https://github.com/sematext/logagent-js/blob/master/LICENSE) shows Apache 2.0 and [package.json](https://github.com/sematext/logagent-js/blob/master/package.json#L38) as well. 
Thanks for the hint!

@otisg  might be able to clarify this. 

PS: If not, it is really easy to become a user e.g. for Logsene free plan https://sematext.com/logsene/ ;)

**Comment by otisg** [comment]
Yes, this is old stuff, we'll clean it up, @erik-stephens

**Comment by megastef** [comment]
https://github.com/sematext/logagent-js/blob/master/bin/logagent.js#L7
