### ISSUE TITLE
Create patterns for key events from /var/log/auth.log, secure, and boot

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#187]
Add patterns for valuable log events from:
- /var/log/auth. log # Debian/Ubuntu
- /var/log/secure # Redhat/CentOS
- /var/log/boot

See https://hackernoon.com/where-do-hackers-live-a-deep-dive-into-my-websites-security-logs-bplo36rz?source=rss

**Comment by megastef** [comment]
Most of the data is already structured when using journald. 
```
> jounralctl -o export -u audit
__CURSOR=s=88ee9e5610c14ea19c2ab57078799793;i=c57a;b=b36e24834ea5431888819e5e3ae6821c;m=160d433c10;t=59eedbf621a07;x=8a792359c327158
__REALTIME_TIMESTAMP=1582118838868487
__MONOTONIC_TIMESTAMP=94711790608
_BOOT_ID=b36e24834ea5431888819e5e3ae6821c
_TRANSPORT=audit
SYSLOG_FACILITY=4
SYSLOG_IDENTIFIER=audit
_UID=0
_AUDIT_LOGINUID=4294967295
_AUDIT_SESSION=4294967295
AUDIT_FIELD_ACCT=root
AUDIT_FIELD_EXE=/usr/sbin/sshd
AUDIT_FIELD_RES=failed
_MACHINE_ID=400518d7368b56325877a28f6f43d32c
_HOSTNAME=scw-gifted-shtern
_AUDIT_TYPE=1100
AUDIT_FIELD_OP=PAM:authentication
AUDIT_FIELD_TERMINAL=ssh
AUDIT_FIELD_HOSTNAME=222.186.52.86
AUDIT_FIELD_ADDR=222.186.52.86
_PID=15461
MESSAGE=USER_AUTH pid=15461 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication acct="root" exe="/usr/sbin/sshd" hostname=222.186.52.86 addr=222.186.52.86 terminal=ssh res=failed'
_SOURCE_REALTIME_TIMESTAMP=1582118838865000
_AUDIT_ID=19399
```

So why analyzing plan text log files ;) - I will have a look.

**Comment by otisg** [comment]
> Most of the data is already structured when using journald.

Right - when/if using journald.  But if one is using Logagent as a log shipper then it's not.

**Comment by megastef** [comment]
Anyhow, i just wanted to share the journald  option - not having those patterns is not a blocker to analyze Linux audit logs. 

You can point `systemd-journal-upload` service to a Logagent instance. See [How To Centralize Linux System Journal](https://sematext.com/docs/logagent/how-to-centralize-linux-system-journal/)

Plus you could activate [GeoIP plugin](https://sematext.com/docs/logagent/output-filter-geoip/) for `audit_field_addr` to get 'attackers' location.  Then you can use [Sematext](https://sematext.com) UI with Top N visualisations to find IP with most failed actions on your host, log alert rules to create alert notifications etc.  

![Screen Shot 2020-02-19 at 19 32 32](https://user-images.githubusercontent.com/7289505/74863735-ab04e280-534e-11ea-8420-d400db1bda89.png)

Example config: https://github.com/sematext/logagent-js/blob/master/config/examples/journald-upload-receiver.yaml

**Comment by otisg** [comment]
OK, one should use approaches described in https://sematext.com/blog/journald-logging-tutorial/
