### ISSUE TITLE
Check Maxmind GeoIP integration

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#190]
Maxmind GeoIP download requires a license key now. 
See: https://github.com/msimerson/maxmind-geolite-mirror/issues/32

The license key can be passed to maxmind-geolite-mirror via MAXMIND_LICENSE_KEY env variable. 

Todo: 

- [ ] Test integration 
- [ ] Update documentation https://github.com/sematext/docs/blob/master/docs/logagent/output-filter-geoip.md

**Comment by otisg** [comment]
I added the doc PR: https://github.com/sematext/docs/pull/179
