### ISSUE TITLE
Make it possible to set max log size

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#20]
Maybe we should have --max-log-size

Maybe we should also have an option that lets one control what happens with logs that are  bigger than --max-log-size.
Such logs could:
* just get dropped, or
* get trimmed to --max-log-size

I assume we should log such situations, so one can see when they have this problem.

**Comment by megastef** [comment]
+1 for cli and config entry 

Currently this is possible with the features from logsene-js (used in logagent-js) by setting environment variables: 
```
LOGSENE_MAX_MESAGE_FIELD_SIZE = 245760 # in bytes
```
The above setting would trims "message" field to 240K. Actually 240K is the new default in logsene-js. 

Do we need the option to drop the message? I think its much better to trim it to the right size according to the field size (schema/field limitations) used in backends.

**Comment by otisg** [comment]
OK.  No need to add drop until we see the real need.
