### ISSUE TITLE
stdin duplicated

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logagent-js#21]
While testing, it took me a while to figure out why I was seeing duplicates.  Not sure if user error on my part, poor usage text, or a bug.  [Here is the part of the code](https://github.com/sematext/logagent-js/blob/3c3184cc86341974f75ce652ca13ae73367beac2/bin/logagent.js#L262) that causes duplicates.  Leaving the `--stdin` flag off produced expected behavior.  Maybe best to remove the `--stdin` option?

**Comment by megastef** [comment]
Thx for reporting, should be easy to fix ..

**Comment by megastef** [comment]
Fixed in npm logagent-js@1.2.21   for 1.x branch. 
https://github.com/sematext/logagent-js/blob/1.x/bin/logagent.js#L592
