### ISSUE TITLE
Publish Logagent ARM 64 container image

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#218]
https://www.google.com/search?q=arm64+node.js

**Comment by adnanrahic** [comment]
### Running natively
Logagent will run natively on any ARM architecture supported by the Node.js runtime.

![nodejs-arm](https://user-images.githubusercontent.com/15029531/78972547-4f650300-7b0e-11ea-8de5-c88d7ae991e8.png)

All you need is install the Node.js runtime on an ARM machine and run the install command just like on any other Node.js runtime:

```bash
sudo npm i -g @sematext/logagent
```

### Running with Docker
For Docker we would need to create dedicated `Dockerfile`s to build Logagent on base ARM images. This issue can be a reference for that until we add the required `Dockerfile`s and configure pushing them to DockerHub.
