### ISSUE TITLE
Access to pattern in transform()

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logagent-js#23]
At first, I didn't know why you'd pass `pattern` into the new filter() option.  After looking at the example, it makes sense now and has me wondering if it makes sense to expose that in transform() as well.  I'm looking for something similar to [logstash's translate filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html).  For small to medium sized dictionaries, I think makes sense to be able to define those once in the pattern instead of having to define inside the transform function.

Before this grows legs, might want to consider a strategy for preventing name clashes between logagent and user's configs.  Letting users define arbitrary fields in the pattern's namespace is likely to cause problems in the future.  Maybe can simply be handled with documentation: "You should namespace anything yourself so we don't clobber it in the future."

**Comment by megastef** [comment]
+1 You read my mind :) But I think its better to do on master. It would be good to expose some other functions like "require", "geoIP.lookup" (existing maxmind object) etc. - currently we look into ways to provide plug-in mechanism, so people could contribute plugins as npm modules for logagent.

**Comment by megastef** [comment]
@erik-stephens is there an urgent need for it in 1.x?  I assume 2.x can still take 1-2 weeks. 
While just adding a parameter with a subset of the pattern definitions e.g. 'transformProperties'  (or the complete pattern definition) to transform() is a little task ...

**Comment by erik-stephens** [comment]
Not a high priority since I can define the dictionaries within the transform function for now.  Thanks!

**Comment by megastef** [comment]
Done in 2.x branch: https://github.com/sematext/logagent-js/blob/2.x/lib/parser/parser.js#L309
Still not relased ...
