### ISSUE TITLE
Stop watching a log file after it's been rotated

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#232]
https://www.npmjs.com/package/tail-forever has unwatch
As does https://github.com/lucagrulla/node-tail

**Comment by megastef** [comment]
Did somebody report that rotated files are still watched? 
Which platforming Linux kernel is used? 
Can you provide more details to reproduce the issue? 

File descriptor changes are monitored automatically in in tailF: https://github.com/mingqi/tailF/blob/master/tail-forever.coffee#L194-L208
The renamed file is closed and the new one opened. 
Please set environment variable DUBUG="tail-forever" to watch the debug output. 

According to past tests Logagent had no issues with rotating log files.

There was a similar issue related to old Linux kernel versions: https://github.com/mingqi/tailF/issues/9
