### ISSUE TITLE
Specify document _id

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logagent-js#24]
I like to define document ids so that I can reprocess logs without adding duplicates.  When I define an `_id` field, it gets renamed to `id`.  Not sure yet if logagent-js is doing this or logsene-js.

**Comment by otisg** [comment]
Is this for shipping logs to Logsene, @erik-stephens ?

**Comment by erik-stephens** [comment]
No, to a private elasticsearch.

**Comment by megastef** [comment]
This should be fixed, when you re-install logagent-js  (it will download latest version of logsene-js). 
See https://www.npmjs.com/package/logsene-js#special-fields-for-indexing
