### ISSUE TITLE
Read file from beginning

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logagent-js#25]
I'd like to be able to start from beginning of file when there is [no stored position](https://github.com/sematext/logagent-js/blob/1.x/lib/fileManager.js#L41).

**Comment by megastef** [comment]
Always? What if the file has several GB? I think such an option should have additional limits. 
E.g. start from beginning, but max last 500 MB.

**Comment by erik-stephens** [comment]
I was thinking an option so as to not muck with current default behavior and give users the choice.  My use case is that I want to [re-]process older files.  I don't see the need for limits since I want to process the entire file regardless of size.

**Comment by megastef** [comment]
See https://github.com/sematext/logagent-js/commit/36b8a988d31ef5f1e2d0d3a85f96f74e2f146242

Fixed 1.x branch,  logagent-js@1.2.24
