### ISSUE TITLE
Stored file position contains "NaN" / invalid position. 

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logagent-js#26]
Spawning in the background and doing a `kill -15 PID` causes [null to be stored as the position](https://github.com/sematext/logagent-js/blob/1.x/lib/fileManager.js#L130):

    2016-07-20T00:01:30.603Z Stop watching /path/to/some-file inode: 147307 pos:NaN

Also, would be nice to have positions stored on SIGINT as well.

**Comment by megastef** [comment]
I doubt that this is related to exit handlers. 
Signals are recognized (SIGINT, SIGQUIT, SIGINT). 
https://github.com/sematext/logagent-js/blob/1.x/bin/logagent.js#L524-#L526

The invalid position is from the tailForever.unwatch() (or a bug in reading the postion before it gets stored). https://github.com/sematext/logagent-js/blob/master/lib/fileManager.js#L141

Was the file renamed? How can this error be re-produced?

**Comment by megastef** [comment]
You could get some more log messages (on stderr, stored e.g. in /var/log/upstart/logagent.log when you use the upstart service). Set following environment variables 
```
export LOG_TAIL_FILE_INFO=1
export DEBUG=1
```

**Comment by erik-stephens** [comment]
Thanks, that will help.  By the way, I'm running this as a spawned process in the shell and not daemonized.  Not renaming files, although I ran it multiple times against different files (full log file vs a small subset).  I'll figure out how to reproduce and probably submit a PR.  A PR for this should go against 1.x branch?

**Comment by megastef** [comment]
Yes please 1.x - 2.x needs to get in shape, working on plugins. 

Do you use ```--diskBufferDir /tmp/logagent```  the file is always stored in this directory. So you run it with different file sets. I could imagine that an old file gets into the list (it was stored), but LA never started a tail process on it, the it tries to unwatch - but I did not check this.

**Comment by erik-stephens** [comment]
I think I was able to [narrow down the issue](https://github.com/mingqi/tailF/issues/5).  My nodejs-fu is not strong enough to add much more insight at this point.  I worry about getting a response since that repo has no commits for almost 2 years.  Hopefully someone here has some insight.

**Comment by megastef** [comment]
Published on npm - I will watch the tailF repository. We should consider a fork or alternative library.

**Comment by erik-stephens** [comment]
Thanks for the workaround but I worry it will try to [read the entire file into memory](https://github.com/mingqi/tailF/blob/master/tail-forever.coffee#L64) since maxSize defaults to -1.  I think I have a fix in [this PR](https://github.com/mingqi/tailF/pull/6).

**Comment by megastef** [comment]
Thanks for catching this! Please ping when a new npm version is available. So I will remove "bufferSize: -1" again.

**Comment by megastef** [comment]
Oh, its on nom already:tail-forever 0.3.12 :)

**Comment by megastef** [comment]
Made a quick test and release with updated dependency. Release: 1.2.25.
