### ISSUE TITLE
[BUG] Wrong url for output-http plugin page

### ISSUE THREAD

**Issue by mcvtec** [sematext/logagent-js#273]
### Problem

On the [page ](https://sematext.com/docs/logagent/plugins/) that lists logagent plugins, the **ouput-http** plugin URL is the same as [output-clickhouse](https://sematext.com/docs/logagent/output-plugin-clickhouse/)

### Solution

Use the correct URL: https://sematext.com/docs/logagent/output-plugin-http/

**Comment by otisg** [comment]
Thanks @mcvtec !
