### ISSUE TITLE
Latest releases not on dockerhub

### ISSUE THREAD

**Issue by dabeck** [sematext/logagent-js#304]
Is there some problem with the CI Pipeline or did you miss to push the latest releases 3.1.x to dockerhub? 

https://hub.docker.com/r/sematext/logagent/tags

**Comment by otisg** [comment]
@dabeck @funkymcb - we'll check this

**Comment by PabloB94** [comment]
@dabeck @funkymcb Thank you for the heads up. The latest version (3.1.2) is now up on DockerHub

**Comment by dabeck** [comment]
Thank you
