### ISSUE TITLE
Logagent CPU usage growing

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#32]
$ npm view logagent-js version
1.2.30

If you hide everything except "nice", I think that is mostly because of Logagent:
https://apps.sematext.com/spm-reports/s/05RV4w2xMG
I do have a few other processes that use nice 19, like Logagent process, but top tells me Logagent is spending more time using the CPU than these other processes...

**Comment by megastef** [comment]
Typically an indicator of more Node.js garbage collection - but this is not growing (over all machines depoyed): https://apps.sematext.com/spm-reports/s/aI5EUuVK73

**Comment by otisg** [comment]
Turns out this is not a problem with Logagent and may be coming from SPM Nodejs agent...
