### ISSUE TITLE
Implement RDBMS input

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#36]
Allow one to provide one or more SQL statements and their execution schedule.

**Comment by megastef** [comment]
This seems to perfect for for PostgreSQL, MySQL, SQLite and MSSQL:
https://www.npmjs.com/package/simple-sql-get

**Comment by otisg** [comment]
And thus maybe also AWS RDS.

**Comment by megastef** [comment]
Here is the mysql-query plugin: https://github.com/sematext/logagent-js/pull/73

**Comment by otisg** [comment]
And mssql-query plugin: #80

**Comment by megastef** [comment]
Closing - input plugins for MySQL, PostgreSQL, MS-SQL are available and documented: 
http://sematext.com/docs/logagent/#plugins

I did not check if MySQL plugin works with AWS RDS - well, it should do the job ...
