### ISSUE TITLE
Json file input (bunyan) and transform

### ISSUE THREAD

**Issue by devnullsp** [sematext/logagent-js#39]
How i transform or filter json log file (v.g. bunyan)?

Thanks.

**Comment by otisg** [comment]
Here's a better place for questions: https://groups.google.com/forum/#!forum/logagent

**Comment by devnullsp** [comment]
Of course, i did but its the only msg at forum o_O,

next questions go there....

Thanks for your work.

**Comment by megastef** [comment]
You could modifiy the parsed object in "globalTransform" defined in patterns.yml.

**Comment by devnullsp** [comment]
ok, thanks, perfect.
