### ISSUE TITLE
Parsing a date error

### ISSUE THREAD

**Issue by msmallcombe** [sematext/logagent-js#4]
I’m trying to parse Fastly’s web logs. Here is an example log line:
107.77.111.34 "-" "-" Fri, 08 Jan 2016 08:59:07 GMT "POST /test" 200 25 "http://www.example.com/articles/" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75 [FBAN/FBIOS;FBAV/46.0.0.54.156;FBBV/18972819;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.2;FBSS/2; FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5]”

Here is my pattern:
- # Fastly
  sourceName: !!js/regexp /fastly/
  match:
    - type: fastly
      regex: !!js/regexp /(^[0-9a-f.:]+)\s+\"(-|.+?)\"\s+\"(-|.+?)\"\s+([a-z]{3}, [0-9]{2} [a-z]{3} [0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}[^\]]*) \"(\S+?)\s{0,1}(\S+?)\" ([0-9|\-]+) ([0-9|\-]+)/i
      fields:       [client_ip,remote_id,user,ts,method,path,status_code,size]
      dateFormat: ddd, dd MMM YYYY HH:mm:ss zzz
      transform: !!js/function >
        function (p) {
          p.message = p.method + ' ' + p.path
        }

This seems to parse correctly, except for the date:
originalLine: 107.77.111.34 "-" "-" Fri, 08 Jan 2016 08:59:07 GMT "POST /test" 200 25 "http://www.example.com/articles/" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75 [FBAN/FBIOS;FBAV/46.0.0.54.156;FBBV/18972819;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.2;FBSS/2; FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5]"
_type:        fastly
client_ip:    107.77.111.34
remote_id:    -
user:         -
ts:           Fri, 08 Jan 2016 08:59:07 GMT
method:       POST
path:         /test
status_code:  200
size:         25
@timestamp:   Invalid Date
message:      POST /test

Is "ddd, dd MMM YYYY HH:mm:ss zzz" the right syntax for a date in this format: "Fri, 08 Jan 2016 08:59:07 GMT"

**Comment by megastef** [comment]
Hi, 
sorry have seen this right now. 
We use http://momentjs.com/docs/#/parsing/  
the correct dateFormat would be "DD MMM YYYY HH:mm:ss zzz"
```
'Fri, 08 Jan 2016 08:59:07 GMT'
> moment(d,'ddd, DD MMM YYYY HH:mm:ss zzz').toDate()
Fri Jan 08 2016 08:59:07 GMT+0100 (CET)
```
but moment.js is assuming local time -> 1 hr difference. 

If you want to have 100% control. Define a JS transform function in the pattern and set there the date, in your case this could work:
```
transform: !!js/function >
        function (p) {
           // p is the parsed object
           moment = require('moment')
           p['@timestamp'] = moment.utc(d,'ddd, DD MMM YYYY HH:mm:ss').toDate().toISOString()
       }
```
->  "'2016-01-08T08:59:07.000Z'"
I hope this helps. 

Anyhow, I will look into options to set default timezone etc.

**Comment by megastef** [comment]
The "invalid date" should not appear anymore. Added moment.isValid() check for dates.

**Comment by otisg** [comment]
@msmallcombe do you still see issues with invalid dates?
