### ISSUE TITLE
Plugin to query systemd/journald logs

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#42]
The plugin should store the timestamp of the last query to make sure it does  not loose logs during restarts.

**Comment by erik-stephens** [comment]
I'm looking for this functionality.  [This thread might be useful](https://github.com/elastic/logstash/issues/1729#issuecomment-57473285), particularly that recipe for piping `journalctl` to logstash.  I couldn't find any nodejs bindings for reading the journal - there's always FFI but makes me nervous.  Will report back how well that recipe works with logagent.

**Comment by erik-stephens** [comment]
Oh, looks like [you are already aware](https://www.quora.com/Does-Systemd-Journal-Remote-already-work-to-ship-the-logs-out-of-CoreOS-boxes) of that option :)

**Comment by megastef** [comment]
Please note the command plugin, example config here for journald logs:
https://github.com/sematext/logagent-js/blob/master/config/examples/journald-elasticsearch.yaml

Not a complete journald plugin as it would be useful to store last query date, and recover from it after a restart, but handy to stream journald logs to Elasticsearch.

**Comment by otisg** [comment]
@megastef can this be closed now?

**Comment by megastef** [comment]
Closing, plugin documentation is here: https://sematext.com/docs/logagent/input-plugin-journald-upload/
