### ISSUE TITLE
multi-line logs without lines being indented by spaces?

### ISSUE THREAD

**Issue by danielnaber** [sematext/logagent-js#47]
I have a log that looks like this (simplified):

	2016-12-08 10:09:16 - [ERROR] - from application - 
	! @72aki4439 - Internal server error, for (POST) [/rest/v1/item] ->
	play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
			at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
			at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
	Caused by: java.lang.NullPointerException: null
			at controllers.RestItem$2.apply(RestItem.java:577) ~[bla-1.0.jar:1.0]

This is one single log entry, but the lines with `!`, `play.api.Application`, and `Caused by` are not indented with spaces. I tried all values for `regex` and `blockStart` that I could think of, but I couldn't get this recognized as a single entry. Is there a way to do this or will I need to change the log format (which isn't trivial, as far as I understand)?

**Comment by megastef** [comment]
Could you please share your pattern definition?

1. you need blockStart to separate the messages e.g. 
```blockStart: !!js/regexp /^\d{4}-\d{2}-\d{2}\s/```
2. the used pattern for the message must end with ```([\s\S]+)``` to catch the newline ```.*```does not catch a newline. Or use multiline modifier for the regex, e.g. ```!!js/regexp / /mypattern/m``` 

Example:
https://github.com/sematext/logagent-js/blob/master/patterns.yml#L141-L148

**Comment by megastef** [comment]
Bad Example:
https://regex101.com/r/zSSwLe/1

Good Example (catching newline)
https://regex101.com/r/zSSwLe/2

**Comment by danielnaber** [comment]
Here's one I've tried. I'm doing this in the context of https://github.com/sematext/logsene-aws-lambda-cloudwatch and they specify logagent-js `1.2.39` as a dependency, is that an issue?

	- # multi line test
	  sourceName: any
	  blockStart: !!js/regexp /^\d{4}-\d{2}-\d{2}\s/
	  match:
		- type: any
		  regex: !!js/regexp /^(\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d) - \[(.*?)\] - from (.+?) -\s([\s|\S]+)/
		  fields: [date,level,from,text]

This works when the "following" lines have a space at the beginning of the line, otherwise not, i.e. otherwise I get several entries. I use this for testing:

    cat myapp.log | bin/logagent.js -y -n myapp -f pattern.yml

**Comment by megastef** [comment]
Have you tried:

```
sourceName: !!js/regexp /.*/
```

Or in your test: 
```
cat myapp.log | bin/logagent.js -y -n any -f pattern.yml
```

I just wonder if the sourceName matches, so Logagent might not use the right pattern. I could try it with 1.x tomorrow. 

I think the lambda-cloudwatch plugin should work with the latest version 2.x as well (could be changed in package.json). We would need to test LA 2.x parser with lambda-cloudwatch, ping @radu-gheorghe

**Comment by danielnaber** [comment]
Thanks, calling with `-n any` works, so it seems my testing was wrong (though I still don't understand why the spaces make a difference when calling with `-n myapp`).

**Comment by megastef** [comment]
Logagent supports multi-line out of the box - I assume it used some fallback configuration, because LA did not recognize the pattern for "any" as a valid match for your "myapp" logs. The default:  A whitespace at the begin of a line causes an action to attach the line to the previous line without leading whitespace - which works for most stack traces without any configuration.
