### ISSUE TITLE
Support Kafka input and output

### ISSUE THREAD

**Issue by radu-gheorghe** [sematext/logagent-js#49]
Plugins for writing to and reading from Kafka should be useful for many setups that have Kafka as a central queue.

One caveat to mention here: reading from Kafka should be synchronous, IMO. That is, ACK the message after it's being successfully sent to the destination. Otherwise, if we ACK on successful read (enqueue), then we simply transfer the messages from Kafka to Logagent's internal queue, which is probably not what we want. One should probably use multiple consumers (Logagent instances? Pipelines within Logagent?) to send data from Kafka to multiple destinations, if we want multiple subscribers.

**Comment by otisg** [comment]
ack on read vs. ack on successful write should be an option IMHO.

**Comment by megastef** [comment]
Just a note: https://www.npmjs.com/package/kafka-node as base for input/output plugins

**Comment by megastef** [comment]
Tracking successful writes might be required for https://github.com/sematext/logagent-js/issues/50 too.

**Comment by martinambrus** [comment]
Another nice feature is to keep the order in which messages arrive and are written. Not sure if this is supported yet in core, so I'm adding it here. Example:

1. message #1 arrives (input stream)
2. transformation is attempted (output-filter)
3. transformation fails
4. message #2 arrives, is transformed and ready to be written via output stream in the meanwhile
5. message #1 transformation is retried and succeeds
6. messages #1 and #2 are written via output stream in the order they arrived (i.e. #2 cannot precede #1)

**Comment by megastef** [comment]
@mbonaci this issue might be a job for you, knowing Kafka very well. 

@martinambrus What do you means with transform (filter/transform functions in LA)? I'm afraid failed transform functions will never succeed - transform functions fail typically because of bugs or invalid/unexpected input. Therefore logagent has no mechanism (yet) to retry transform functions.

**Comment by martinambrus** [comment]
Ah, I see. We've been in a need of stream processor capable of keeping the order of messages coming from Kafka and then being written to another Kafka topic once they have been transformed (or augmented, i.e. some data were added to the original data and then saved).

Thank you for your answer. It would seem that I'm yet to find a solution that's capable of this functionality or code it myself :P

**Comment by otisg** [comment]
@martinambrus What you describe above would mean that a transformation that failed would block all subsequent transformations.  Nobody likes blocking in pipelines... Maybe there's a reason this stuff doesn't exist? :)

That said, if you see how this can be accomplished here to fit your needs (maybe via a **plugin** that, when used, will block and order things as you've described), and ideally providing something generally useful without creating negative side-effects, a PR would be very welcome!

**Comment by martinambrus** [comment]
@otisg you would be correct about the blocking in a certain case. The failed transformation (let's say MySQL is down for a couple of seconds, so we can't get the additional data) in our case is resolved in 2 steps:

1. keep retrying the failed transformation after a timeout (500ms) up until X number of retries is reached, then fail and exit the process
2. while doing this, all subsequent transformations are being either:
  * queued up at the transformer's part until the first one finishes (if they share the same transformer) 
  * or
  * are performed immediately (if they use different transformer) and queued at output stream's part until the one failing transformation succeeds (and is placed in correct order in the output queue)
  * once failing transformation(s) resolve, messages queued at the ouput stream's part are saved, which preserves the correct order

It gets a little more complicated than that (like when we need to keep the limit of messages in the output queue to 10 at maximum per one batch saved)... and now that I'm reading this all, I guess the complexity would be why nobody really did that before :-D

Anyways, NodeJS is a wonderful tool to do this but I'm afraid it would be too much of a challenge to implement this into logagent-js as a plugin. I think I'll go with a custom NodeJS logger in this case. Thanks for responding to the comment and all the best with this project :)

**Comment by otisg** [comment]
Look at Apache Flume, it maaaaay have what you need.

**Comment by megastef** [comment]
In node [kafka-streams](https://www.npmjs.com/package/kafka-streams) seems to be an interesting package, see word count example:
https://github.com/krystianity/kafka-streams/blob/master/examples/wordCount.js

Streams make sure that the order is preserved. Using [through2](https://www.npmjs.com/package/through2) you could hook any transform function in the stream via pipe, combined with [retry](https://www.npmjs.com/package/retry) it could make this task much simpler. E.g. when you call the through2 callback only when retry reports a success. As long you don't call through2 callback function the read stream of the pipe is blocked. When a tasks really fails, you could throw an error to break the pipeline and restart the process. 

Just to share a few ideas with @martinambrus

**Comment by martinambrus** [comment]
thanks guys, will definitely have a closer look at those :)

**Comment by megastef** [comment]
Kafka Input: https://github.com/sematext/logagent-js/blob/master/lib/plugins/input/kafka.js
Kafka Output: https://github.com/sematext/logagent-js/blob/master/lib/plugins/output/kafka.js
Examples and Test: 
https://github.com/sematext/logagent-js/blob/master/config/examples/kafka-stdout-yml.yml
https://github.com/sematext/logagent-js/tree/master/kafka-test

Thank you @fbalicchia for contributing.  We have to create documentation for Kafka and some other plugins @radu-gheorghe see issue #85
