### ISSUE TITLE
Implement Elasticsearch Index API

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#52]
So one can easily feed Logagent from other data sources that can output to Elasticsearch.

**Comment by fbalicchia** [comment]
Hi,

Could you please explain better what you mean ?
From reference issue what I've understand is that you prefer use
ES bulk API instead of implement lumberjack-protocol server (input)

I'm I in wrong ? IMHO can be useful to have lumberjack protocol input
cause in this case we can forward traffic arrive from beat agent
WDYM ?

**Comment by megastef** [comment]
We thought of implementing Elasticsearch bulk API as input: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-bulk.html

**Comment by fbalicchia** [comment]
Hi,
I started to work on this issue and I've complete input part. 
Please see
[input](https://github.com/fbalicchia/logagent-js/blob/master/lib/plugins/input/esbulk.js)
My idea is to, after some check on input side like NDJSON ecc.ecc, emit message body and forward to output side  . I'd like to avoid use esclient.js, even though I saw that there is already dependency, in favor of  Logsene endpoint but  I have not yet seen whether it is possible to do such a thing 

var client = new elasticsearch.Client({
  host: 'localhost:9090',
  log: 'debug'
});

client.bulk(data.msg);

WDYT ?

**Comment by megastef** [comment]
Hi @fbalicchia - I think you are on the wrong track. 

`logagent-input-elasticsearch-http`  should behave like an Elasticsearch server for bulk indexing. 
So tools like FileBeat could ship data to Logagent, where the smart things happen ;) 

This means:
1. Start http server on default port 9200
2. Handle post requests to '/_bulk' 
3. Read the body, which has 2 lines per document. The first one is an isntruction like "index" (or delete/update) with metatadata like index name and type. The second line is the actual document, which needs to be indexed. Here is an example for 2 documents: 
```
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "2" } }
{ "field1" : "value2" }
```
We would support only `index` opertion for the beginning (no delete/update)
4. Emit objects with this structure to Logagent eventEmitter: 
```{ "field1" : "value1", "_index" : "test", "_type" : "type1", "_id" : "1" }```
Create a context object with ```{source: 'input-elasticsearch-http', index=test}``` attached to the generated event (ES ouput plugin uses context.index field). 
5. Generate the HTTP response for Elasticsearch clients - this must only match the expected format.
    We can't actually say that creation will be successful for the whole processing chain (this would require tracking status and output filters might drop some docs - so I'm not sure if it makes sense to care about it). Therefore we have to create a "fake" to acknowledge the reception of the documents.  
```{
   "took": 30,
   "errors": false,
   "items": [
      {
         "index": {
            "_index": "test",
            "_type": "type1",
            "_id": "1",
            "_version": 1,
            "result": "created",
            "_shards": {
               "total": 2,
               "successful": 1,
               "failed": 0
            },
            "created": true,
            "status": 201
         }
      }
]
```

Elasticsearch output plugin (or others) could interpret the `_index` and ` _type` fields (and they do it already as far I remember, if not we can adjust it ...). 

Once done this test should work: 
```
$ logagent --config elasticsearch-input.http.yml 
$ cat requests
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }
$ curl -s -H "Content-Type: application/x-ndjson" -XPOST localhost:9200/_bulk --data-binary "@requests"; echo
{"took":7, "errors": false, "items":[{"index":{"_index":"test","_type":"type1","_id":"1","_version":1,"result":"created","forced_refresh":false}}]}
```

**Comment by megastef** [comment]
Closing. Done see https://sematext.com/docs/logagent/input-plugin-elasticsearch-http/
