### ISSUE TITLE
Make Logagent work with Node 7.4

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#53]
Tried upgrading node to 7.4 yesterday and Logagent failed to start because of missing deps...

**Comment by megastef** [comment]
This seems to be a general problem with 7.4.
First run
npm i npm@latest -g
Then update  node to 7.4

**Comment by otisg** [comment]
And then it works?  Or are you saying it doesn't work with 7.4 at all?

**Comment by megastef** [comment]
This is not a logagent issue - logaagent works with node 7.4.0 once npm and node 7 are correctly installed. Npm v4 must be installed before node gets updated to v7, when  you upgrade a system (at least this is one of the possible workarounds). 
Relevant issues:
https://github.com/nodejs/node/issues/9377
https://github.com/npm/npm/issues/14438

**Comment by megastef** [comment]
One more link to solve the npm problems after upgrade to node 7: 
http://stackoverflow.com/questions/40308623/cannot-find-module-internal-fs-afer-upgrading-to-node-7/40406482#40406482
