### ISSUE TITLE
Add tests for GeoIP functionality

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#54]
This functionality depends on MaxMind DB and they seem to like changing what their functions return, so tests are needed to catch that.

**Comment by megastef** [comment]
Since today the test script checks for geoip record: https://github.com/sematext/logagent-js/blob/master/test/test.js#L40

**Comment by otisg** [comment]
So.... closable?

**Comment by megastef** [comment]
Closing. We still have https://github.com/sematext/logagent-js/issues/30 open
