### ISSUE TITLE
Logagent-setup fails to create init.d script

### ISSUE THREAD

**Issue by ashiddo11** [sematext/logagent-js#64]
logagent-setup script should create an init.d script but it doesn't when using debian weezy. Currently it tries to create a systemd file and then fails to start the service.

**Comment by megastef** [comment]
Right, there is currently no support for init.d - only upstart, systemd and launchd (Mac OS X).

**Comment by megastef** [comment]
@ashiddo11 could you contribute a function for the init.d script generation? 
https://github.com/sematext/logagent-js/blob/master/bin/logagent-setup.sh

**Comment by megastef** [comment]
I wonder why systemd file is created. So systemctl is installed, but systemd is not used to start services? 

https://github.com/sematext/logagent-js/blob/master/bin/logagent-setup.sh#L154
What is the output of `systemctl` on your system?

**Comment by megastef** [comment]
Did you run the setup as super user? It needs root permissions.

**Comment by ashiddo11** [comment]
Yes I ran it as root. 
```
$ sudo systemctl
-bash: systemctl: command not found
```
I'll create a function for the init.d script and create a PR when I get a chance

**Comment by ashiddo11** [comment]
Created PR https://github.com/sematext/logagent-js/pull/66
