### ISSUE TITLE
GeoipEnabled isn't getting picked up from config file

### ISSUE THREAD

**Issue by ashiddo11** [sematext/logagent-js#65]
when setting geoipEnabled to true in the config file, logagent fails to detect it and doesn't download any maxmind files. However, if i remove the geoipEnabled option from config and set it through CLI or an ENV variable it works. Also, setting geoipEnabled to true in config and CLI or an ENV doesn't work.

**Comment by megastef** [comment]
Could please share the relevant config section? As far I see LA makes a string compare and the YML config parser might turn `true` in a boolean value. Please try

```
options:
  geoipEnabled: 'true'
```

**Comment by ashiddo11** [comment]
Yeah that fixed it
