### ISSUE TITLE
Make it easier to debug log parsing

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#69]
c.f. http://stackoverflow.com/questions/42653362/sematext-logagent-debugging-patterns

**Comment by otisg** [comment]
To debug patterns you could use the logagent cli:
e.g.
cat test.log | logagent --stdin -n radius.log -f /etc/sematext/patterns.yml

There are some more options for logagent that might help, like --verbose.
https://github.com/sematext/logagent-js/blob/master/docs/cli-parameters.md

e.g.
cat sample.log | logagent -c /etc/sematext/logagent.conf --stdin -n 2017-05-23.log --verbose

**Comment by megastef** [comment]
Setting 'debug: true' in patterns.yml prints detailed info about matched patterns. 
https://github.com/sematext/logagent-js/blob/master/patterns.yml#L36

**Comment by otisg** [comment]
Prints to console or some log?

**Comment by megastef** [comment]
Prints to the console (stderr, so It does not interfere with UNIX pipe for stdin/stdout).

**Comment by otisg** [comment]
I couldn't find any info about this in the docs.  Should we add it to http://sematext.com/docs/logagent/config-file/ ?
Maybe also to http://sematext.com/docs/logagent/parser/ ?
And maybe this could be the beginning of http://sematext.com/docs/logagent/faq which doesn't exist yet?

**Comment by megastef** [comment]
Available in  http://sematext.com/docs/logagent/faq
