### ISSUE TITLE
Logagent-js should have on-disk buffering

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#7]
spm-agent has:
* Buffering metrics to disk in case of network outages (using NeDB)
* Limit the file size of buffers

logagent-js should have that, too.

**Comment by megastef** [comment]
Logagent had already this option, but only via environment variable LOGSENE_TMP_DIR. The latest change in the cli tool enables disk buffer by default and the directory can be changed e.g. via cli parameter ```--logsene-tmp-dir /tmp```. The upstart, systemd and launchd configurations have this option set to ```/tmp```. The new version is available on [npm](https://www.npmjs.com/package/logagent-js).

**Comment by otisg** [comment]
This should be documented in the README.  Looking at the README I could not tell logagent-js can buffer data locally in case it cannot be shipped for some reason.  This is a major feature for a log shipper!
