### ISSUE TITLE
Borrow run.sh and Dockerfile from SBB Logagent image

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#71]
From https://hub.docker.com/r/schweizerischebundesbahnen/logagent/
- run.sh: https://github.com/SchweizerischeBundesbahnen/docker-logagent/blob/master/bin/run.sh
- Dockerfile: https://github.com/SchweizerischeBundesbahnen/docker-logagent/blob/master/Dockerfile

... so we can build a Logagent image people can use.
We should probably add a link to it over at https://sematext.com/docs/logagent/#related-packages and also under Logagent > Install > Docker (doesn't exist yet)

**Comment by megastef** [comment]
Please note this PR: https://github.com/SchweizerischeBundesbahnen/docker-logagent/pull/4

**Comment by komljen** [comment]
@megastef please check this pull request https://github.com/sematext/logagent-js/pull/104
