### ISSUE TITLE
Output to AWS Elasticsearch?

### ISSUE THREAD

**Issue by bloodcarter** [sematext/logagent-js#88]
Is there a support for AWS Elasticsearch? They require signed requests.

**Comment by megastef** [comment]
Yes, the Elasticsearch output supports client certificates. If you need user and password, you could specify it in the URL. See documentation:
http://sematext.com/docs/logagent/output-elasticsearch/#http-and-https-options

**Comment by bloodcarter** [comment]
No, AWS doesn't use typical creds. They require Signature Version 4 Signing Process http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by megastef** [comment]
It seems that a static header configuration would not be sufficient, this could be done already.

**Comment by bloodcarter** [comment]
Actually, if you were using elasticsearch-js, then all you need is add connectionClass and awsConfig paramaters and include "http-aws-es" as a dep. It does all heavy lifting:
```
  const client = new elasticsearch.Client({
    connectionClass: opts['aws-credentials'] ? require('http-aws-es') : undefined,
    awsConfig: opts['aws-credentials'] ? AWS.config.loadFromPath(opts['aws-credentials']) : undefined,
  })
```

**Comment by otisg** [comment]
+1 for a PR, if possible

**Comment by bloodcarter** [comment]
@otisg I could do a PR, but it seems like you use logsene-js, not elasticsearch-js.

**Comment by otisg** [comment]
Maybe logsene-js can "sniff out" it needs to talk to AWS ES and use that only in that case?

Btw....AWS ES for logs?  Isn't that the most expensive ES option around?

**Comment by bloodcarter** [comment]
@otisg I'm not very familiar with  logsene-js , I just saw it is not based on elasticsearch-js, that's all. Regadring AWS ES pricing, if think this is offtopic, but I just have a lot of credits)

**Comment by megastef** [comment]
Changing logsene-js would be challenging because it would need to re-implement the signing procedure to set the right HTTP headers and the error handling might need to be adjusted to AWS. 

We could add aws-elasticsearch output plugin to Logagent using `elasticsearch.client` - sounds simple. The disadvantage would be the lost of disk buffering for failed Elasticsearch requests, which is part of logsene-js. 

I think disk-buffering would need to be different for AWS ES because AWS ES needs to sign each request including a timestamp - simply storing failed HTTP requests to disk to repeat them later would probably not work well with AWS ES. We would need to store the JSON documents and create new HTTP requests for the retry procedures. I think we have another issue open to make disk-buffers more general.

**Comment by bloodcarter** [comment]
@megastef I think creating aws-elasticsearch output plugin would be just enough for the most cases. Keep me posted on it. Because right now we intergrated logagent into our prod system like that, and this solution is a bit ugly:
`JSON_ENRICHMENT_ENABLED=false logagent ./logs/debug.log | pino-elasticsearch --host https://my-url.es.amazonaws.com --port 443 -c ./aws_config.json`

**Comment by megastef** [comment]
@bloodcarter Please see commit https://github.com/sematext/logagent-js/commit/54bed7ec280c52b3542b16ec8fd8c798c4b22d68 
I've added an untested skeleton for output-aws-elasticsearch - @bloodcarter could you please continue on it? (testing, providing an example config file with the AWS ES property names, ...)? 

I had no example of the aws_config.json and our config should look like: 

```
output:
  module: output-aws-elasticsearch
  host: https://my-url.es.amazonaws.com
  index: indexName
  type: typeName
  auth: 'user:password'
  awsConfig:
    # aws config entries here ... ? please complte required properties
    region: ...
```


Thanks in advance!

**Comment by bloodcarter** [comment]
@megastef Isn't it better and safier to just put a path to the aws_config.json file into the logagent conf?

**Comment by megastef** [comment]
A config file pointing to a config file? Anyhow we would need to specify format. Feel free to change the constructor ... i just wanted ro give you a quick start for the Logagent plugin. Of course we would better use bulk instead of index function etc...

**Comment by bloodcarter** [comment]
Yeah, but this aws_config.json is an autogenerated file what you can donwload from AWS website. It contains something like that:
`{ "accessKeyId": "xxxxxxx", "secretAccessKey": "yyyyyyyyyyyyyyy", "region": "us-east-1" }`

If you think that it's a good idea to expose the credentials beyond aws_config.json, then you may want to add those two fields to your config: awsAccessKey and awsSecretKey.

**Comment by megastef** [comment]
Ok, got it :) 
Here is an example configuration file: 
https://github.com/sematext/logagent-js/blob/master/config/examples/output-aws-elasticsearch.yml

You could test by installing directly from git: 
```
npm i -g sematext/logagent-js
logagent --config yourConfig.yml
# aws-config.json should be in the current directory or you have to specify absolute path
```

Enjoy. I could only test error case as I have no AWS ES instance to test. 
Once you confirm that it is working, we could add it to the release. Feel free to contribute a PR enhancements (e.g. error handling/retransmit/bulk indexing).

**Comment by bloodcarter** [comment]
I confrim that it works!

But this line is unnecessary for AWS ES:
`    auth: 'user:password'`

And also what does this code actually do?
```
    log:
      - type: 'stdio'
        levels: [] # empty array to supress ES node client logs
```

And I didn't see any console errors when elasticsearch refuses to add something into it's index (for instance when you are trying to feed it a different types of variables with the same name). Maybe add printing out such errors? This implies not only AWS ES, but ES in general.

**Comment by megastef** [comment]
Thanks! 

The "log" property is an option for the nodejs elasticsearch client library. For debugging you could configure it to dump every query and result to console. 
E.g.: 

```
log:
      - type: 'stdio'
        levels: 
          - 'error' 
          - 'warning'
          - 'info'
```

The entry `levels: []` disables all log output to console for "elasticserach" client library - which should be the standard in Logaagent because we don't like verbose logging in a log shipper ...
See: https://stackoverflow.com/questions/24703589/how-do-i-turn-logging-off-for-elasticsearch-in-node-js

**Comment by bloodcarter** [comment]
OK. I got it. Let me know when release is out. I will switch out prod system to it then.

**Comment by megastef** [comment]
Released on npm. Install
```
npm i -g @sematext/logagent@2.0.84
```

**Comment by megastef** [comment]
Documentation released: http://sematext.com/docs/logagent/output-plugin-aws-elasticsearch/

**Comment by bloodcarter** [comment]
Nice! Closing.
