### ISSUE TITLE
How to turn off parser completely

### ISSUE THREAD

**Issue by bloodcarter** [sematext/logagent-js#89]
I already have logs in the format I needed. How do I turn parsing off?

**Comment by megastef** [comment]
Do you use JSON? Then Logagent detects JSON and skips regex parser.

You could set the environment variable PATTERN_MATCHING_ENABLED=false to disable parser.

**Comment by bloodcarter** [comment]
This is not working:
PATTERN_MATCHING_ENABLED=false bash -c 'logagent /home/ec2-user/workspace/logs/debug.log'

**Comment by megastef** [comment]
Yes, this is the result of the JSON parser. As we need a timestamp in the right format for Elasticsearch, therefore LA adds `@timestamp` to every log. In addition, it transforms Bunyan log level to a readable severity field. Let me check if we could add a flag to disable additional fields. So you want the JSON 1:1?

**Comment by bloodcarter** [comment]
Yes. I want JSON 1:1

**Comment by megastef** [comment]
Ok, try @sematext/logagent v2.0.79. And set the new environment variable:

```
export ENABLE_JSON_ENRICHMENT=false
```

From my local test console:
```
export ENABLE_JSON_ENRICHMENT=false
 echo '{"msg": "hello"}' | bin/logagent.js 
2017-09-20T08:55:32.462Z pid[83990] init filter: inputFilter
2017-09-20T08:55:32.464Z pid[83990] init filter: outputFilter
2017-09-20T08:55:32.465Z pid[83990] init plugins
2017-09-20T08:55:32.465Z pid[83990] ../lib/plugins/input/stdin
2017-09-20T08:55:32.487Z pid[83990] ../lib/plugins/output/stdout
2017-09-20T08:55:32.567Z pid[83990] Logagent initialized
{"msg":"hello"}
2017-09-20T08:55:34.572Z pid[83990] terminate reason: stdin closed
```

BTW, why don't you use pino-elasticsearch? Any trouble with it?  I've seen you forked it.

**Comment by bloodcarter** [comment]
Currently I use pino-elasticsearch to push logs to AWS Elasticsearch from nodejs stdout, but I want to switch from reading from nodejs process to reading from file, so I still need a solution for tailing the log file, restoring the last point, etc.

Still no luck:
```
[ec2-user@ip-172-31-16-252 workspace]$ ENABLE_JSON_ENRICHMENT=false logagent /home/ec2-user/workspace/logs/debug.log
2017-09-20T09:00:10.061Z pid[8361] init filter: inputFilter
2017-09-20T09:00:10.063Z pid[8361] init filter: outputFilter
2017-09-20T09:00:10.064Z pid[8361] init plugins
2017-09-20T09:00:10.065Z pid[8361] ../lib/plugins/input/stdin
2017-09-20T09:00:10.082Z pid[8361] ../lib/plugins/output/stdout
2017-09-20T09:00:10.092Z pid[8361] ../lib/plugins/input/files
2017-09-20T09:00:10.184Z pid[8361] Watching file:/home/ec2-user/workspace/logs/debug.log from position: 56415
2017-09-20T09:00:10.270Z pid[8361] Logagent initialized
{"pid":8597,"hostname":"ip-172-31-16-252","name":"dasha-0.1.0","level":"30","v":1,"@timestamp":"2017-09-20T09:00:13.616Z","message":"Starting Dasha Mk 4 (0.1.0)...","severity":"info"}
```

**Comment by megastef** [comment]
Hmm, maybe npm cache? 
```
sudo npm i -g @sematext/logagent@latest
/usr/local/bin/logagent -> /usr/local/lib/node_modules/@sematext/logagent/bin/logagent.js
/usr/local/bin/logagent-windows -> /usr/local/lib/node_modules/@sematext/logagent/bin/logagent-windows.js
/usr/local/bin/logagent-setup -> /usr/local/lib/node_modules/@sematext/logagent/bin/logagent-setup.sh
/usr/local/bin/logagent-uninstall -> /usr/local/lib/node_modules/@sematext/logagent/bin/logagent-uninstall.sh
/usr/local/lib
└── @sematext/logagent@2.0.79 

imac:logagent-js stefan$ export ENABLE_JSON_ENRICHMENT=false
imac:logagent-js stefan$ echo '{"msg": "hello"}' | bin/logagent.js 
2017-09-20T09:09:58.639Z pid[84205] init filter: inputFilter
2017-09-20T09:09:58.641Z pid[84205] init filter: outputFilter
2017-09-20T09:09:58.642Z pid[84205] init plugins
2017-09-20T09:09:58.642Z pid[84205] ../lib/plugins/input/stdin
2017-09-20T09:09:58.663Z pid[84205] ../lib/plugins/output/stdout
2017-09-20T09:09:58.742Z pid[84205] Logagent initialized
{"msg":"hello"}
2017-09-20T09:10:00.749Z pid[84205] terminate reason: stdin closed
```
npm should show @sematext/logagent@2.0.79 
I see you did not use "export", maybe the env variable setting was not passed to the logagent process.

**Comment by bloodcarter** [comment]
I am sorry. I didn't notice, you published a new version. I confrim that ENABLE_JSON_ENRICHMENT=false works now. Thanks!
Put this into the docs, because somebody maybe needs it just like me.

Now I am going to use it like this:
```sh
$ ENABLE_JSON_ENRICHMENT=false logagent ./logs/debug.log | pino-elasticsearch --host https://my-url.us-east-1.es.amazonaws.com --port 443 -c ./aws_config.json
```

But actually this is an ugly workaround, it would be better if your elasticsearch plugin support AWS Elasticsearch (I opened another issues on that).

But again! Thanks. Closing this.

**Comment by megastef** [comment]
Please note, we use logsene-js to index data. This module added some fields (hostname, ip, severity) before indexing in Elasticsearch. We just added support for ENABLE_JSON_ENRICHMENT to it: https://github.com/sematext/logsene-js/commit/ecc96313700daf2ff07afcda076017253f986d44

So please re-install logagent to get latest logsene-js logsene-js@1.1.50 sub-module to avoid getting additional fields in your Elasticsearch. 

For AWS you should use Logagent Elasticsearch output.

**Comment by bloodcarter** [comment]
As I stated here https://github.com/sematext/logagent-js/issues/88, I can't use Logagent Elasticsearch output for AWS. Or give me a working example.

**Comment by otisg** [comment]
@megastef Note the naming inconsistency: PATTERN_MATCHING_ENABLED vs. ENABLE_JSON_ENRICHMENT.  Maybe we should change ENABLE_JSON_ENRICHMENT to JSON_ENRICHMENT_ENABLED now.

**Comment by megastef** [comment]
Ok, done renaming ENABLE_JSON_ENRICHMENT -> JSON_ENRICHMENT_ENABLED in Release 2.0.81

**Comment by bloodcarter** [comment]
Why also not to add JSON_ENRICHMENT_ENABLED option into config file? To the parser section, like:
```
parser:
   json_enrichment_enabled: false
```

OR simplier to switch off parser completely:
```
parser:
   enabled: false
```
