### ISSUE TITLE
Make it easy to exclude originalLine

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#9]
Shipping originalLine plus the structured version of it means shipping 2x more bytes.  It should be easy to include/exclude shipping of originalLine.  As a matter of fact, maybe originalLine should not be shipped  by default.

**Comment by megastef** [comment]
Please note the patterns.yml includes a the setting "originalLine: true". 
https://github.com/sematext/logagent-js/blob/master/patterns.yml#L14

We could set it the default value to false, and add a command line option ```--include-original```  to activate originalLine again. So nobody would need to touch patterns.yml.

**Comment by otisg** [comment]
Seems reasonable...

**Comment by otisg** [comment]
I think this can be closed now?

**Comment by megastef** [comment]
Not done yet .. so we keep the issue open.

**Comment by megastef** [comment]
Done. --include-original-line true/false. Default false https://github.com/sematext/logagent-js/commit/c73c63d0b93a39fb3b363523115cc11fe2e35523
