### ISSUE TITLE
Add GELF Output Plugin

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#94]
The GELF output plugin might need a few mappings from Logagent default fields to  GELF fields:
- 'severity' -> 'level' 
- 'message' -> 'full_message'
- '@timestamp' -> 'timestamp'

https://www.npmjs.com/package/graygelf#lograwgelf

See also:
https://sematext.com/docs/logagent/plugins/#for-developers-how-logagent-plugins-work

**Comment by megastef** [comment]
CC: @fbalicchia you mentioned interest in GELF compatibility of Logagent in the past. So I opened this issue here.

**Comment by fbalicchia** [comment]
Hi @megastef,
yes, gelf out plugin is missing I'll do it soon

**Comment by megastef** [comment]
I think this is done: https://github.com/sematext/logagent-js/blob/master/lib/plugins/output/gelfout.js
And the documentation is here: https://sematext.com/docs/logagent/output-plugin-gelf/
